# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pizza.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpizza.proto\"\x07\n\x05\x45mpty\"\x14\n\x04Size\x12\x0c\n\x04size\x18\x01 \x01(\x05\x32*\n\x08PizzaRPC\x12\x1e\n\x0bSetFileSize\x12\x05.Size\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pizza_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_SIZE']._serialized_start=24
  _globals['_SIZE']._serialized_end=44
  _globals['_PIZZARPC']._serialized_start=46
  _globals['_PIZZARPC']._serialized_end=88
# @@protoc_insertion_point(module_scope)
